---
title: "Homework 03 - ENVS-193DS"
output: html_document
date: "2025-05-25"
---

**GitHub Repository:** [ENVS-193DS_homework-03](https://github.com/mmakigill/ENVS-193DS_homework-03)

```{r}
# Load packages
library(tidyverse)
library(here)
library(gt)       
library(janitor)  
library(ggplot2)
library(readr)

```

*Part Two: Problems*

[A] To compare my response variable and it's fluctuation between categories in my data, I could calculate the mean water footprint in gallons for each meal type (omnivore, vegetarian etc.) to compare the impact of different dietary choices on water use. Different diets include foods with varying water demands (meat vs. vegetables), which will provide an informative comparison of how food choices could reduce overall daily water consumption.

Problem 1:
```{r}
# Reading in the data

Meal_Data <- read_csv("data/Meal_Data.csv")

# Create the plot
ggplot(Meal_Data, aes(x = Meal_Type, y = Water_Footprint, fill = Meal_Type)) +
  geom_jitter(width = 0.2, shape = 21, color = "black", size = 2, alpha = 0.6) +  # show individual data points
  stat_summary(fun = mean, geom = "bar", width = 0.5, color = "black", position = position_dodge(0.9)) +
  scale_fill_manual(values = c("Omnivore" = "Brown", "Vegetarian" = "Dark Green", "Vegan" = "Light Blue", "Pescatarian" = "Coral", "Carnivore" = "Red")) +
  labs(
    title = "Mean Water Footprint by Meal Type",
    x = "Meal Type",
    y = "Water Footprint (gallons)"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")
```
